

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-local
    ports:
      - "27017:27017" # Map MongoDB's default port to localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data locally in your device

volumes:
  mongodb_data: